# H2 database connection URL, username, and password
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Hibernate (JPA) settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Expose the H2 Console for testing in local environment
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Disable Liquibase
spring.liquibase.enabled=false
logging.level.org.springframework.security=DEBUG

