spring.application.name=homework
server.port=8081
spring.profiles.active=dev

# Actuators
management.endpoints.web.exposure.include=*

# Health endpoint
management.endpoint.health.show-details=always
management.health.disk_space_health.enabled=true
management.health.ramdom.enabled=true