spring.datasource.url=jdbc:postgresql://localhost:5432/products?currentSchema=prod
spring.datasource.username=prod
spring.datasource.password=prod
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/changelog-master-prod.xml